apiVersion: apps/v1
kind: Deployment
metadata: 
  name: my-app
spec: 
  replicas: 2

  selector:
    matchLabels:
      app: my-web-app

  template:
    metadata:
      name: my-web-app
      labels:
        app: my-web-app
    spec:
      containers: 
        - name: custom-image
          image: tasneem73/nginx-test
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80

