apiVersion: v1
kind: Pod
metadata:
  name: my-web-app
spec: 
  containers:
    - name: nginx-app
      image: tasneem73/nginx-test
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80      